### ISSUE TITLE
ALC285 output doesn't work on all 4 speakers

### ISSUE THREAD

**Issue by koluris** [dkoluris/HP-ENVY-13-AH0002-OpenCore#1]
We need to investigate the reason that ALC285 current Audio Layouts (11, 21, 31, 52) do not output sound on all 4 speakers of this laptop.

**Comment by koluris** [comment]
What I've done so far is to dump the ALC285 audio codec with OpenCore, insert it into PinConfigurator app, sanitize it, and export the changes into AppleALC's PinConfigs.kext. But after that I am kind of lost with what to do for `Platforms` and `Layout` XML files.

**Comment by rholelaw** [comment]
With VoodooHDA the audio comes out of the bottom speakers and not the top. Could that provide a clue?

**Comment by koluris** [comment]
That is very interesting, let me verify this. Is there a specific version I should use?

**Comment by rholelaw** [comment]
Just the latest one from sourceforge. No extra config or boot-args.  
It sometimes sets the sound output device as headphones on boot for some reason. Might have to manually select Speakers from the Sound Panel.

**Comment by koluris** [comment]
My attempt completely disabled the sound output :( Care to share EFI or something? Maybe I need to add SSDT patches with VoodooHDA compared to AppleALC?

**Comment by rholelaw** [comment]
Will share my efi soon as I get in. Probably be an hour from now. Will comment when it’s done. I have no patches. VoodooHDA just worked.

**Comment by rholelaw** [comment]
https://github.com/rholelaw/HP_Envy_13-ah0501na_OpenCore

^Thats with VoodooHDA. Front 2 speakers work. Back don't.
Just replace my DSDT.aml with yours since I've got the dGPU.

**Comment by koluris** [comment]
I tried and retried, and VoodooHDA just disabled whole audio engine. I really don't know what to say.

**Comment by rholelaw** [comment]
That’s strange. It’s the same audio system. Could it be something in my DSDT that’s different?  Obviously the dGPU is but maybe something about how it sets up the audio is also different.

**Comment by djimc** [comment]
Hey guys, 
I've just created an account so I can post this. I don't know if this will help, but Applealc has been updated to v 1.5.5 (Added ALC285 layout-id 71 for Spectre x360 ap0xxx by jpuxdev)

I have tried it and both sets of speakers are available in sound pref pane as individual devices with each of them working and producing sound on its own. I created a Multi-Output device using the built in tool from Apple and all 4 speakers now produce sound. The downside is there is no volume control at all when using the multi-output device. All the speakers are blasting at 100%
![Screenshot 2020-12-13 at 17 57 54](https://user-images.githubusercontent.com/75943429/102017042-12bc6c00-3d6d-11eb-8bbb-43c5e1d26aad.png)

I hope this helps solving the issue. 
Best!

**Comment by djimc** [comment]
Update: 
Soundflower to the rescue. All 4 speakers are working with volume control. Perfect temp solution. 

Cheers

**Comment by koluris** [comment]
Omg, this is such a wonderful progress. Going to try this in a couple of hours, many thanks! @djimc

**Comment by djimc** [comment]
@dkoluris
Many thanks. The credit goes to jpuxdev for the layout for Spectre x360. I just experimented. 
Don't forget you also need Soundflowerbed, so you can select the newly created aggregate device as Soundflower output. Otherwise you won't get any sound at all. 

Simply put, 
Select Soundflower as default output within Mac OS and the aggregate device as Soundflower output. 

Best!

**Comment by koluris** [comment]
Thanks for pointing the most correct direction. I was able to make it work 4 speakers without SoundFlowerBed. Open MIDI setup, and add a new unified output device, check both those desired outputs on the left, and finally go to Sound Preferences where you select that new unified output as your main audio device!

**Comment by djimc** [comment]
That's what I did initially. Do you have volume control? I am only usin Soundflower for the volume control.

**Comment by koluris** [comment]
Yeah, it works with the F buttons for me, let me check the volume slider.

**Comment by koluris** [comment]
Ah yes you are right, doesn't work, lol

**Comment by koluris** [comment]
Checking for possible solutions

**Comment by koluris** [comment]
Hell, I was adjusting the single channel volume. It seems that your solution is the most plausible, thanks again!

**Comment by djimc** [comment]
Thanks for the extensive testing. I was kind of hoping there was a way to achieve this without Soundflower. Anyway, let's hope there is an "out of the box" solution soon. 

Cheers

**Comment by koluris** [comment]
Yeah, still... awesome stuff!

**Comment by koluris** [comment]
I mean in the bottomline, this is Apple's limitation lol.

**Comment by koluris** [comment]
https://github.com/dkoluris/HP-ENVY-13-AH0002-OpenCore updated with everything we know

**Comment by koluris** [comment]
Leaving this issue open just in case we nail it with proper audio volume adjust.

**Comment by koluris** [comment]
Going to try this one tomorrow: https://github.com/rlxone/MultiSoundChanger

**Comment by djimc** [comment]
Fingers crossed there will be a layout combining the two output devices as one so we don't need the aggregate device. That would be the best experience, but until then - this workaround works for me. 
I haven't tested JACK on Mac OS. I might give that a try as well. 
I'm still checking  AppleALC project updates from time to time though.

**Comment by djimc** [comment]
I also tested MultiSoundChanger. It's definitely better, because it does not route audio. If one does not need to record their audio stream, MultiSoundChanger is the better option.
