### ISSUE TITLE
SDHC reader doesn't work

### ISSUE THREAD

**Issue by koluris** [dkoluris/HP-ENVY-13-AH0002-OpenCore#2]
Even though there is some development for the RTS card readers on the following repo: https://github.com/sinetek/Sinetek-rtsx, I wasn't able to make it work just yet.

Needs further investigation.

**Comment by rholelaw** [comment]
Created a Pull Request with the fixed DSDT + Driver that you linked above. 

SDReader speed is limited to 5MB/sec read and write. 
Mount/unMount can be slow with multi-partitions on one microSD card.
File transfer works reliably with Catalina 10.15.5.  Tested with a 30GB Time Machine backup and restore.  
Reader (along with the Touchscreen) can be seen and used by the installer if you create a backup USB drive to boot from with this OC EFI folder. Restored the Time Machine backup just fine direct from the microSD.

**Comment by koluris** [comment]
Thanks! I ended up using this release: https://github.com/cholonam/Sinetek-rtsx/releases/tag/Releases%2Fv2.2 which seems to provide better speed overall. Again, thanks for your valuable contribution!
