### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by 4Spike** [dkoluris/HP-ENVY-13-AH0002-OpenCore#4]
I found the ENVY-13-AH0002CA and ENVY-13-AH0004TU are same, because they's use same BIOS.

After some of my tests, i confirm that your EFI is more suitable for my device, so i rebuild my EFI.

Now my laptop use better, thank you.

My Repositories: https://github.com/ongengi/HP-ENVY-13-AH0004TU-Hackintosh-OpenCore

**Comment by koluris** [comment]
Thank you so much for your feedback, it means a lot to me! Indeed, I always try to add the bare minimum to make a hackintosh work, se we all know where we stand correct, and whatever is still missing becomes easier to find :)

I really hope we can solve this problem with the Audio, this laptop has very good B&O speakers and mine is missing the bottom speakers which is the bass.

If you improve anything in the future let me know as well!
