### ISSUE TITLE
MX150 and UHD620 along with work?

### ISSUE THREAD

**Issue by mehmetyukcell** [dkoluris/HP-ENVY-13-AH0002-OpenCore#6]
This model has the dedicated Nvidia MX150 GPU along with the Intel UHD620 iGPU. How to Two GPU work?

**Comment by koluris** [comment]
Only one can work, the UHD620, let me redirect you to a friend of mine that has a fork of this repo specifically tailored for this model: https://github.com/rholelaw/HP_Envy_13-ah0501na_OpenCore

**Comment by mehmetyukcell** [comment]
Thanks...
