### ISSUE TITLE
Recovery and reset NVRam entries on boot picker

### ISSUE THREAD

**Issue by fdaprano** [dkoluris/HP-ENVY-13-AH0002-OpenCore#7]
I am currently using your Opencore settings (with some modifications) for my AH0999NL and everything is working (still need to investigate about CardReader and Bluetooth) but Recovery and Reset NVRAM entries are missing from the boot picker.

Here's what I did so far:
- Disabled these Kexts to attempt to make it boot properly since my model doesn't have a touchscreen and got stuck on loading screen: VoodooGPIO, VoodooI2CServices, VoodooI2C, VoodooI2CHID
- Installed Catalina on a partition alongside an existing Windows installation
- Copied OC in my SSD EFI folder, added OpenCore.efi UEFI entry and set as default boot in BIOS

When computer starts, it displays a nice graphical boot picker and there are entries to launch MacOS and Windows (both are working fine) but Recovery and Reset NVRAM entries are gone. 
How to solve?

Thanks for your good work!

**Comment by koluris** [comment]
Hey, thanks for the good words. The key you are looking for on the `config.plist` is `<key>HideAuxiliary</key>`. I have set this to `true` by default. You can get the same NVRAM & Recovery entries by pressing the space key on the boot screen.

If you have removed VoodooI2C, then you need to make sure that `VoodooInput.kext` exists inside `VoodooPS2Controller.kext` on `Plugins` folder. If you do that just reorganize your `config.plist` and you're good to go.

**Comment by fdaprano** [comment]
Thanks for your precious advice, now the entries display as I wanted.

I added VoodooInput to my config.plist, but I don't know if it's really needed, I didn't have issues with my trackpad and keybpard before adding it. However my system log says this:
`2020-07-19 12:34:07.416512+0200  localhost kernel[0]: Refusing new kext me.kishorprins.VoodooInput, v1.0.6: a prelinked copy with a different executable UUID is already present.`

Just another doubt: Is it possible that removing VoodooI2C may interfere with IntelBluetooth and CardReader? Because none of them are working at the moment: "Bluetooth: not Available" and "This computer doesn't contain any Apple Internal Memory Card Readers." 
Thanks again.

**Comment by koluris** [comment]
Are you able to see all your USB ports mapped correctly? Bluetooth is attached to one of the intel USB lanes.

**Comment by fdaprano** [comment]
This is my USB ports mapping:
![image](https://user-images.githubusercontent.com/33355684/87875659-17097680-c9d3-11ea-98fe-c864554c93c7.png)
Don't know why there are chinese comments though. The Port which Bluetooth is connected should be the 0x06 which is active, but BT still not available.

**Comment by koluris** [comment]
Show me your System -> Peripherals on Hackintool please.

**Comment by fdaprano** [comment]
Here it is
![image](https://user-images.githubusercontent.com/33355684/87876382-2212d580-c9d8-11ea-8cff-263aaec673bc.png)

**Comment by koluris** [comment]
This is weird, you are missing HS05, and the address on HS06 is not correct. Take a look:
<img width="1920" alt="Στιγμιότυπο 2020-07-19, 5 01 19 μμ" src="https://user-images.githubusercontent.com/31432553/87876570-9b62f600-c9e1-11ea-8839-78e5f9fdfd9e.png">
<img width="1920" alt="Στιγμιότυπο 2020-07-19, 5 01 25 μμ" src="https://user-images.githubusercontent.com/31432553/87876574-a3bb3100-c9e1-11ea-91e4-c81dec0cc98b.png">

**Comment by koluris** [comment]
Can you dump your DSDT.aml and send it to me? Not the one I provide on the repo, but your own system's DSDT.

**Comment by fdaprano** [comment]
Here's my DSDT.aml dump.
[DSDT.zip](https://github.com/dkoluris/HP-ENVY-13-AH0002-OpenCore/files/4943819/DSDT.zip)

**Comment by koluris** [comment]
Unfortunately this is not your untouched DSDT.aml dump. It contains my own edits inside. Best way to do this is to run Clover and press `F4` on the boot.

**Comment by fdaprano** [comment]
Looks like Opencore injects ACPI even when you are not booting MacOS. I created the old dump in Windows using SSDTTime but it was booted via Opencore. I repeated the dump but booting Windows directly from BIOS (bypassing Opencore). This dump should be clean, I did a checksum and it has a different MD5 than the old one. 
[DSDT.zip](https://github.com/dkoluris/HP-ENVY-13-AH0002-OpenCore/files/4944253/DSDT.zip)

Sorry and thanks again.

**Comment by fdaprano** [comment]
Ok, I figured it out. After many investigations about USB port mapping, I found that SMBios ProductName is important if you create a custom USB mapping, then I remembered that during my previous trial and errors, I changed the SMBios product name to MacBookPro14,2 while your USBPorts.kext has it mapped to MacBookPro14,1. Reverted back to MacBookPro14,1 and now Bluetooth and Camera are working.
Is there a reason to choose MacBookPro14,1 over MacBookPro14,2?

Many many thanks for your time, your work is awesome! I am happy now.

**Comment by koluris** [comment]
Hey, glad you found it:
- Compared untouched DSDT, we have nearly identical, so that's good (you can use my own edited)
- I chose `MacBookPro14,1` because it's the last pro model without a Touch Bar, so we don't have to use one extra kext

**Comment by fdaprano** [comment]
Ok everything is clearer now. Very glad to find someone with patience and willing to help a complete newbie like me. Thanks again.

**Comment by koluris** [comment]
Not a newbie :) You were able to fix your own problem, good going! Thanks for the kind words.
