### ISSUE TITLE
TouchScreen 15in model

### ISSUE THREAD

**Issue by andrescera** [dkoluris/HP-ENVY-13-AH0002-OpenCore#8]
hello, your repo has been very useful for me as a parting point at the moment I'm stuck on three things Bluetooth, sd card and touchscreen are not working for me, I even have exactly the same model 7265, would please tell what the device names are for sd card and touch screen on dsdt.aml, I'll publish my device's config once it's done thank you so much

**Comment by andrescera** [comment]
SD Card, Blueetooth were solved by using SSDT-RHUB.aml, what I have not been able to do is enabling Touch screen by using ssdt, I've made this one:
```
DefinitionBlock ("", "SSDT", 2, "HPENVY", "TPL1", 0x00000000)
{
    External (_SB_.PCI0.I2C1, DeviceObj)
    External (_SB_.PCI0.I2C1.TPL1, DeviceObj)
    External (_SB_.PCI0.I2C1.TPL1.SBFB, FieldUnitObj) 
    External (_SB_.PCI0.I2C1.TPL1.SBFG, FieldUnitObj) 

    Scope (_SB.PCI0.I2C1.TPL1)
    {
        Method (_STA, 0, NotSerialized)  // _STA: Status
        {
            If (_OSI ("Darwin"))
            {
                Return (0x0F)
            }

            Return (0x0F)
        }
           
       Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
            {
                If (_OSI ("Darwin"))
                {
                    Return (ConcatenateResTemplate (SBFB, SBFG))
                } Else{
                \_SB.PCI0.I2C1.TPL1._CRS ()
                }
                
                
                }
        
    }
}


```

**Comment by koluris** [comment]
Checking to see where's the touchscreen patch on my DSDT, will get back to you.

**Comment by koluris** [comment]
Your patch for the touch screen seems to inject the right stuff. Do you have the XOSI patch applied too?

**Comment by andrescera** [comment]
Even applying _OSI TO XOSI it won't get touchpad working, as you can see my dsdt is slightly different from yours but it should work :( everything else is working including Camera, Bluetooth, trackpad, keyboard, backlight, etc etc...

[DSDT.aml.zip](https://github.com/dkoluris/HP-ENVY-13-AH0002-OpenCore/files/5900135/DSDT.aml.zip)

Few things are missing such as changing brightness using the keyboard, and only 4 speakers are working as mine uses ALC 295 Instead as 285 (at the moment I'm using layout-id=1

[SSDT-BKeys-Q1CQ1D.zip](https://github.com/dkoluris/HP-ENVY-13-AH0002-OpenCore/files/5900182/SSDT-BKeys-Q1CQ1D.zip)

**Comment by koluris** [comment]
There's a Gitter channel about VoodooI2C, and since you are very knowledgable I am pretty sure you will get a lot of valuable information if you ask about the Touch Screen there. You know there might be subtle differences which makes it not as easy to enable the Touch Screen same as mine. What is the exact HP model you have?

**Comment by andrescera** [comment]
i didn't even know there was such a thing like gitter, thank you so much it's a HP ENVY x360 - 15m-cn0012dx
